# vim:syntax=python
from numscons import GetNumpyEnvironment
from numscons.core.misc import built_with_mingw

env = GetNumpyEnvironment(ARGUMENTS)


bld = Builder(action = "$DLLWRAPCOM", suffix = ".dll")
env['BUILDERS']["Static2Dll"] = bld

env.Static2Dll('blas', source = "libblas.a", DLLWRAPFLAGS = "--export-all-symbols", DLLWRAPLIBS = "g2c")
