# vim:syntax=python
from numscons import GetNumpyEnvironment
env = GetNumpyEnvironment(ARGUMENTS)

# cython tool not loaded by default
env.Tool("cython")
env.DistutilsPythonExtension(source = "yop.py")

# You could build the source file manually too
# yop = env.Cython("yop.py")
# env.DistutilsPythonExtension(source = yop)
