# vim:syntax=python
from numscons import GetNumpyEnvironment, NumpyCheckLibAndHeader

env = GetNumpyEnvironment(ARGUMENTS)

config = env.NumpyConfigure(custom_tests = {'NumpyCheckLibAndHeader' : NumpyCheckLibAndHeader})
if not config.NumpyCheckLibAndHeader('sndfile', 'sf_open', 'sndfile.h', section = 'sndfile'):
    print "sndfile not found, this package cannot work without sndfile !"
config.Finish()
